services:
  telegram-bot:
    build: .
    container_name: bot-telegram-omega
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8095:8080"
    volumes:
      - ./logs:/app/logs
    dns:
      - 8.8.8.8
      - 1.1.1.1
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep 'python' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
